[project]
name = "bankservice"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "fastapi",
    "python-multipart",
    "uvicorn",
    "libsql",
    "bcrypt",
    "PyJWT",
    "kafka-python",
    "google-genai",
    "chromadb",
    "elasticsearch>=8.0.0",
    "openai",
    "ddgs",
    "pypdf",
    "pillow",
    "arize-phoenix",
    "arize-phoenix-otel",
    "arize-phoenix-client",
    "openinference-instrumentation-openai",
    "openinference-instrumentation-langchain",
    "openinference-semantic-conventions",
    "langgraph",
    "langchain-openai",
    "langchain-core",
    "redis",
    "jupyter",
    "pytest",
    "pytest-cov",
    "matplotlib",
    "pandas",
]

[tool.vercel]
entrypoint = "backend.app:app"
